/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelos;


import BaseDeDatos.ConexionMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


/**
 *
 * @author usuario
 */
public class ModificacionBajaPlan extends javax.swing.JFrame {

    /**
     * Creates new form ModificacionBajaPlan
     */
    
        /**
     * Creates new form PlanVariable
     */
    private String UID;
    private String motivo_sncS;
    private String rubroS="0";
    private Integer ramosSelected=0;
    int[] ramosIdx = new int[100];
    
    public ModificacionBajaPlan(String userId) {
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        UID=userId;
        initComponents();
        prepcmbDevs();
        habilitar();
        inhabilitar();
        
        txtSucursal.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void removeUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void insertUpdate(DocumentEvent e) {
              updateCombo();
            }

            public void updateCombo() {
                ConexionMySQL mysql= new ConexionMySQL();
                Connection cn= mysql.Conectar();

                String sSQL="", idSuc="";
                idSuc= txtSucursal.getText();

                sSQL= "select descripcion from sucursal where idSucursal = '"+idSuc+"'";

                try
                {
                    Statement st= cn.createStatement();
                    ResultSet rs= st.executeQuery(sSQL);
                    if (rs.next())
                        try {
                            jcomSucursal.setSelectedItem(rs.getString("descripcion")); 
                        } catch (IllegalStateException e) {}
                    else
                        jcomSucursal.setSelectedItem(null);
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
        txtIdProveedor.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void removeUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void insertUpdate(DocumentEvent e) {
              updateCombo();
            }

            public void updateCombo() {
                ConexionMySQL mysql= new ConexionMySQL();
                Connection cn= mysql.Conectar();

                String sSQL="", idProv="";
                idProv= txtIdProveedor.getText();

                sSQL= "select pr.razon_social as razon from proveedor as pr where pr.idproveedor = '"+idProv+"'";

                try
                {
                    Statement st= cn.createStatement();
                    ResultSet rs= st.executeQuery(sSQL);
                    if (rs.next())
                        try {
                            jcomProveedor.setSelectedItem(rs.getString("razon")); 
                        } catch (IllegalStateException e) {}
                    else
                        jcomProveedor.setSelectedItem(null);
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlbProveedor = new javax.swing.JLabel();
        txtIdProveedor = new javax.swing.JTextField();
        jlbMotivoSNC = new javax.swing.JLabel();
        btnNuevoPlan = new javax.swing.JButton();
        btnConsultasPlan = new javax.swing.JButton();
        jcomProveedor = new javax.swing.JComboBox<>();
        jcomMotivo = new javax.swing.JComboBox<>();
        jlbVigencia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbAplicacion = new javax.swing.JLabel();
        jrbMensual = new javax.swing.JRadioButton();
        jrbSemanal = new javax.swing.JRadioButton();
        btnSeleccion = new javax.swing.JButton();
        jlbAccion = new javax.swing.JLabel();
        txtAccionComercial = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jlbDesde = new javax.swing.JLabel();
        jlbHasta = new javax.swing.JLabel();
        dpFechaHasta = new org.jdesktop.swingx.JXDatePicker();
        dpFechaDesde = new org.jdesktop.swingx.JXDatePicker();
        lblPorcent = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTitDev = new javax.swing.JLabel();
        lblTitDevMes = new javax.swing.JLabel();
        cmbDevMes = new javax.swing.JComboBox<>();
        lblTitDevSem = new javax.swing.JLabel();
        cmbDevSem = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jlbTitTipoMotSNC = new javax.swing.JLabel();
        rbCompra2 = new javax.swing.JRadioButton();
        rbVenta2 = new javax.swing.JRadioButton();
        lblCompN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCompName = new javax.swing.JLabel();
        lblListaPrecios = new javax.swing.JLabel();
        txtListaPrecios = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jlbSucursal = new javax.swing.JLabel();
        txtSucursal = new javax.swing.JTextField();
        jcomSucursal = new javax.swing.JComboBox<>();
        txtRamos = new javax.swing.JLabel();
        jcomRamos = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jlbTitTipoMotSNC1 = new javax.swing.JLabel();
        rbCompra1 = new javax.swing.JRadioButton();
        rbVenta1 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jlbAplicacion1 = new javax.swing.JLabel();
        jrbMensual1 = new javax.swing.JRadioButton();
        jrbSemanal1 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Condiciones del Plan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbProveedor.setBackground(new java.awt.Color(51, 204, 0));
        jlbProveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbProveedor.setText("Proveedor:");
        jlbProveedor.setMaximumSize(new java.awt.Dimension(60, 14));
        jlbProveedor.setMinimumSize(new java.awt.Dimension(60, 14));
        jlbProveedor.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jlbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        txtIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 62, -1));

        jlbMotivoSNC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbMotivoSNC.setText("Motivo SNC:");
        jlbMotivoSNC.setMaximumSize(new java.awt.Dimension(60, 14));
        jlbMotivoSNC.setMinimumSize(new java.awt.Dimension(60, 14));
        jlbMotivoSNC.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jlbMotivoSNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 905, -1));

        btnNuevoPlan.setText("Nuevo Plan");
        btnNuevoPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPlanActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 115, 32));

        btnConsultasPlan.setText("Consultas");
        btnConsultasPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasPlanActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultasPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 117, 32));

        jcomProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(jcomProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 990, -1));

        jcomMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomMotivoActionPerformed(evt);
            }
        });
        jPanel1.add(jcomMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 990, -1));

        jlbVigencia.setText("Vigencia Devengamiento:");
        jPanel1.add(jlbVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 154, 23));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbAplicacion.setText("Aplicación:");

        jrbMensual.setText("Mensual");
        jrbMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMensualActionPerformed(evt);
            }
        });

        jrbSemanal.setText("Semanal");
        jrbSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSemanalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbSemanal)
                    .addComponent(jlbAplicacion)
                    .addComponent(jrbMensual))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlbAplicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMensual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbSemanal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        btnSeleccion.setText("Seleccionar Articulos");
        btnSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 230, 40));

        jlbAccion.setText("Acción Comercial: ");
        jPanel1.add(jlbAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 425, 118, -1));

        txtAccionComercial.setText("0");
        txtAccionComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccionComercialActionPerformed(evt);
            }
        });
        jPanel1.add(txtAccionComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 87, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1115, 513, 110, 40));

        jlbDesde.setText("Desde");
        jPanel1.add(jlbDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jlbHasta.setText("Hasta");
        jPanel1.add(jlbHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));
        jPanel1.add(dpFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 140, -1));
        jPanel1.add(dpFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 140, -1));

        lblPorcent.setText("%");
        jPanel1.add(lblPorcent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 425, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitDev.setText("Devengamiento:");

        lblTitDevMes.setText("Dia del Mes:");

        cmbDevMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTitDevSem.setText("Dia de la Semana:");

        cmbDevSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitDevMes)
                            .addComponent(cmbDevMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitDevSem)
                            .addComponent(cmbDevSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitDev))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTitDev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitDevMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDevMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitDevSem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDevSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbTitTipoMotSNC.setText("Tipo de Motivo SNC:");

        rbCompra2.setText("Compra");
        rbCompra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCompra2ActionPerformed(evt);
            }
        });

        rbVenta2.setText("Venta");
        rbVenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVenta2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTitTipoMotSNC)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rbCompra2)
                        .addGap(17, 17, 17)
                        .addComponent(rbVenta2)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jlbTitTipoMotSNC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCompra2)
                    .addComponent(rbVenta2))
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 160, -1));

        lblCompN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCompN.setText("[N]");
        jPanel1.add(lblCompN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Comprador:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, -1, 19));

        lblCompName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCompName.setText("[COMP_NAME]");
        jPanel1.add(lblCompName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 164, -1));

        lblListaPrecios.setText("Lista de precios:");
        jPanel1.add(lblListaPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 225, -1, -1));
        jPanel1.add(txtListaPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, -1));

        jlbSucursal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbSucursal.setText("Sucursal:");
        jlbSucursal.setMaximumSize(new java.awt.Dimension(60, 14));
        jlbSucursal.setMinimumSize(new java.awt.Dimension(60, 14));
        jlbSucursal.setPreferredSize(new java.awt.Dimension(60, 14));

        jcomSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jlbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcomSucursal, 0, 991, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jcomSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 1170, 40));

        txtRamos.setText("Ramos:");
        jPanel1.add(txtRamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jcomRamos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcomRamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomRamosActionPerformed(evt);
            }
        });
        jPanel1.add(jcomRamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 380, -1));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbTitTipoMotSNC1.setText("Tipo de Motivo SNC:");

        rbCompra1.setText("Compra");
        rbCompra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCompra1ActionPerformed(evt);
            }
        });

        rbVenta1.setText("Venta");
        rbVenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVenta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jlbTitTipoMotSNC1)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rbCompra1)
                .addGap(18, 18, 18)
                .addComponent(rbVenta1)
                .addGap(14, 14, 14))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jlbTitTipoMotSNC1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCompra1)
                    .addComponent(rbVenta1))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 160, -1));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbAplicacion1.setText("Aplicación:");

        jrbMensual1.setText("Mensual");
        jrbMensual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMensual1ActionPerformed(evt);
            }
        });

        jrbSemanal1.setText("Semanal");
        jrbSemanal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSemanal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbSemanal1)
                    .addComponent(jlbAplicacion1)
                    .addComponent(jrbMensual1))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jlbAplicacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMensual1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbSemanal1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        jRadioButton1.setText("jRadioButton1");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProveedorActionPerformed

    private void btnNuevoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPlanActionPerformed
        ///// HABILITA TODOS LOS PUNTOS NUEVAMENTE
        habilitar();
    }//GEN-LAST:event_btnNuevoPlanActionPerformed

    private void btnConsultasPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasPlanActionPerformed
//        ConsultaVariables ventanaConsulta= new ConsultaVariables();
//        ventanaConsulta.setExtendedState(JFrame.MAXIMIZED_BOTH);
  //      ventanaConsulta.setVisible(true);
    }//GEN-LAST:event_btnConsultasPlanActionPerformed

    private void jcomProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomProveedorActionPerformed

        ///realizamos la conexion con la bdd.

        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();

        ///ingresamos la consulta
        String sSQL="", razon="";
        razon=(String) jcomProveedor.getSelectedItem();

        sSQL= "select pr.idproveedor as id from proveedor as pr where pr.razon_social LIKE '%"+razon+"%' order by id";

        try
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);

            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                try {
                    txtIdProveedor.setText(rs.getString("id"));
                } catch (IllegalStateException e) {}
                //this.jcomArticulo.removeAllItems();
                //jcomClaseArticulo();

            }
            // jcomProveedor.transferFocus();
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jcomProveedorActionPerformed

    private void jcomMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomMotivoActionPerformed
        ///realizamos la conexion con la bdd.

        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();

        ///ingresamos la consulta
        String sSQL="", motivo="";
        motivo=(String) jcomMotivo.getSelectedItem();

        sSQL= "select idmotivo_snc as id from motivo_snc where descripcion LIKE '%"+motivo+"%' order by id";

        try
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);

            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                if(!jcomMotivo.getSelectedItem().toString().equals("")){
                    //txtMotivoSNC.setText(rs.getString("id"));
                    motivo_sncS=rs.getString("id");
                }else{
                    //txtMotivoSNC.setText("");
                    motivo_sncS="";
                }
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jcomMotivoActionPerformed

    private void resetFormControls(){
        dpFechaDesde.setDate(null);
        dpFechaHasta.setDate(null);
    }
    private void prepcmbDevs(){
        cmbDevMes.removeAllItems();
        cmbDevSem.removeAllItems();
        for(Integer cont=1;cont<=31;cont++){
            cmbDevMes.addItem(cont.toString());
        }
        cmbDevSem.addItem("Lunes");
        cmbDevSem.addItem("Martes");
        cmbDevSem.addItem("Miercoles");
        cmbDevSem.addItem("Jueves");
        cmbDevSem.addItem("Viernes");
        cmbDevSem.addItem("Sabado");
        cmbDevSem.addItem("Domingo");
        enableDevItems(1);
    }   
    private void enableDevItems(Integer btns){
        if(btns==1){
            cmbDevSem.setEnabled(false);
            lblTitDevSem.setEnabled(false);
            cmbDevMes.setEnabled(true);
            lblTitDevMes.setEnabled(true);
        }else{
            cmbDevSem.setEnabled(true);
            lblTitDevSem.setEnabled(true);
            cmbDevMes.setEnabled(false);
            lblTitDevMes.setEnabled(false);
        }
    }
    private void jrbMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMensualActionPerformed
        enableDevItems(1);
    }//GEN-LAST:event_jrbMensualActionPerformed

    private void jrbSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSemanalActionPerformed
        enableDevItems(2);
    }//GEN-LAST:event_jrbSemanalActionPerformed

    
    private Integer setDiaDevengamiento(){
        Integer valorDia=0;
        if(jrbMensual.isSelected()){
            //ESTA SELECCIONADO DEVENGAMIENTO MENSUAL
            valorDia=Integer.valueOf((String)cmbDevMes.getSelectedItem());
        }else{
            //ESTA SELECCIONADO DEVENGAMIENTO SEMANAL
            String valorCmb = cmbDevSem.getSelectedItem().toString();
            switch(valorCmb){
                case "Domingo": valorDia=1;
                                break;
                case "Lunes": valorDia=2;
                                break;
                case "Martes": valorDia=3;
                                break;
                case "Miercoles": valorDia=4;
                                break;
                case "Jueves": valorDia=5;
                                break;
                case "Viernes": valorDia=6;
                                break;
                case "Sabado": valorDia=7;
                                break;
            }
        }
        return valorDia;
    }
    
    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
        if (dpFechaDesde.getDate()==null ||dpFechaHasta.getDate()==null){
            String mensaje="Verificar fechas!!!";
            JOptionPane.showMessageDialog(null, mensaje);
        }else{
            //conexión a la bdd
            ConexionMySQL mysql= new ConexionMySQL();
            Connection cn= mysql.Conectar();
            ///FECHA ACTUAL
            java.util.Date date = new java.util.Date();
            java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(date);
            ///STRING A UTILIZAR
            String idProve="", tipoDePlan="",fechaActual="", sucursal="0", idComprador="",idRubro="";
            String motivoSNC="", idArt="0", fechaDesde="", fechaHasta="";
            String accionComercial="", tipoDeAplicacion="";
            String listaPre="";
            if (txtListaPrecios.getText().equals("")){
                listaPre="TODAS";
            }else{
                listaPre=txtListaPrecios.getText();
            }
            // cantCopias="0"
            String sSQL="";
            String mensaje;
            String estado="PENDIENTE";
            ///campos a cargar
            idProve= txtIdProveedor.getText();
            tipoDePlan= "VARIABLE";
            fechaActual= fecha;
            idComprador= lblCompN.getText();
            sucursal= txtSucursal.getText();
            idRubro= ramosSelected.toString();
            motivoSNC= motivo_sncS;
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            fechaDesde= sdf1.format(dpFechaDesde.getDate()).toString();
            fechaHasta= sdf1.format(dpFechaHasta.getDate()).toString();
            accionComercial=txtAccionComercial.getText();

            if (this.jrbMensual.isSelected()==true){
                tipoDeAplicacion="Mensual";
            }
            else{
                if (this.jrbSemanal.isSelected()==true){
                    tipoDeAplicacion="Semanal";}
            }
            idArt=null;
            //SETEAMOS EL DIA DE DEVENGAMIENTO
            Integer diaDev = setDiaDevengamiento();
            ///creamos la consulta sql
            if (accion.equals("Insertar"))
            {
                sSQL="INSERT INTO plan_descuento (Proveedor_idproveedor, tipo_plan,fechaActual,"
                + "Usuario_idusuario,Sucursal_idSucursal,Sector_idsector,Motivo_SNC_idMotivo_SNC,"
                + "fecha_Devengamiento_Desde, fecha_Devengamiento_Hasta, accion_comercial, aplicacion,dia_devengamiento,Articulo_idArticulo,lista_precio,estado) "+
                "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                mensaje="Operación Satisfactoria";
            }
            try
            {
                PreparedStatement pst= cn.prepareStatement(sSQL);
                pst.setString(1, idProve );
                pst.setString(2, tipoDePlan);
                pst.setString(3, fechaActual);
                pst.setString(4, idComprador);
                pst.setString(5, sucursal);
                pst.setString(6, idRubro);
                pst.setString(7, motivoSNC);
                pst.setString(8, fechaDesde);
                pst.setString(9, fechaHasta);
                pst.setString(10,accionComercial);
                pst.setString(11,tipoDeAplicacion);
                pst.setString(12,diaDev.toString());
                pst.setString(13,idArt);
                pst.setString(14,listaPre);
                pst.setString(15,estado);

                int n = pst.executeUpdate();

                if (n>0)
                {
                    mensaje="Operación Satisfactoria";

                    JOptionPane.showMessageDialog(null, mensaje);

                    habilitar();//habilita los campos para la carga de datos
                    inhabilitar();
                    SeleccionArticulosVariables ventanaArticulos= new SeleccionArticulosVariables(idProve);
                    //ventanaArticulos.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    ventanaArticulos.setVisible(true);
                    resetFormControls();
                }

            }

            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btnSeleccionActionPerformed

    private void txtAccionComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccionComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccionComercialActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        ModificacionBajaPlan.this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jcomSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomSucursalActionPerformed
        ///realizamos la conexion con la bdd.

        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();

        ///ingresamos la consulta
        String sSQL="", sucursal="";
        sucursal=(String) jcomSucursal.getSelectedItem();

        sSQL= "select idSucursal as id from sucursal where descripcion LIKE '%"+sucursal+"%'";

        try
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);

            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                try {
                    txtSucursal.setText(rs.getString("id"));
                } catch (IllegalStateException e) {}
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jcomSucursalActionPerformed

    private void jcomRamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomRamosActionPerformed
        // TODO add your handling code here:
        if(jcomRamos.getSelectedIndex()!=-1){
            ramosSelected=ramosIdx[jcomRamos.getSelectedIndex()];
        }
    }//GEN-LAST:event_jcomRamosActionPerformed

    private void rbCompra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCompra1ActionPerformed
        // TODO add your handling code here:
        jcomClaseMotivoMenu(1);
    }//GEN-LAST:event_rbCompra1ActionPerformed

    private void rbVenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVenta1ActionPerformed
        // TODO add your handling code here:
        jcomClaseMotivoMenu(2);
    }//GEN-LAST:event_rbVenta1ActionPerformed

    private void jrbMensual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMensual1ActionPerformed
        enableDevItems(1);
    }//GEN-LAST:event_jrbMensual1ActionPerformed

    private void jrbSemanal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSemanal1ActionPerformed
        enableDevItems(2);
    }//GEN-LAST:event_jrbSemanal1ActionPerformed

    private void rbCompra2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCompra2ActionPerformed
        // TODO add your handling code here:
        jcomClaseMotivoMenu(1);
    }//GEN-LAST:event_rbCompra2ActionPerformed

    private void rbVenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVenta2ActionPerformed
        // TODO add your handling code here:
        jcomClaseMotivoMenu(2);
    }//GEN-LAST:event_rbVenta2ActionPerformed

     String accion="Insertar";
     private void loadCmbTPlan(Integer tipo){
        
    }
       /////////////////////////////////////////////////////////////////////////////
    //////////////CLASES PARA HABILITAR E INHABILITAR LOS MENUS//////////////////
    /////////////////////////////////////////////////////////////////////////////
    void habilitar(){
       
        //GENERO GRUPO DE RADIO BUTTONS
        lblListaPrecios.setEnabled(true);
        txtListaPrecios.setEnabled(true);
        txtRamos.setEnabled(true);
        jcomRamos.setEnabled(true);
        buttonGroup1.add(jrbMensual);
        buttonGroup1.add(jrbSemanal);
/*        btnGrpTipoPlan.add(rbCompra);
        btnGrpTipoPlan.add(rbVenta);
        jrbMensual.setSelected(true);
        rbCompra.setSelected(true);*/
        
        //CARGO EL COMBO DE TIPO SNC CON LAS COMPRAS
        loadCmbTPlan(1);
       ///Habilitar los botones.
       dpFechaDesde.setEnabled(true);
       dpFechaHasta.setEnabled(true);
       btnConsultasPlan.setEnabled(true);

       btnNuevoPlan.setEnabled(true);
       btnSalir.setEnabled(true);
       btnSeleccion.setEnabled(true);
       
        ///Habilitar los jCOMBOX
       //jcomArticulo.setEnabled(true);
       
       jcomMotivo.setEnabled(true);
       jcomProveedor.setEnabled(true);

       jcomSucursal.setEnabled(true);
       
       ///Habilitar las etiquetas.
       jlbAccion.setEnabled(true);
       jlbAplicacion.setEnabled(true);
       //jlbArticulo.setEnabled(true);
       
       lblPorcent.setEnabled(true);
       jlbDesde.setEnabled(true);
       jlbHasta.setEnabled(true);
       jlbMotivoSNC.setEnabled(true);
       jlbProveedor.setEnabled(true);

       jlbSucursal.setEnabled(true);
       jlbVigencia.setEnabled(true);
       jlbTitTipoMotSNC.setEnabled(true);
       ///Habilitar Radio botones
       jrbMensual.setEnabled(true);
       jrbSemanal.setEnabled(true);
       lblTitDev.setEnabled(true);
       lblTitDevMes.setEnabled(true);
       lblTitDevSem.setEnabled(true);
       cmbDevMes.setEnabled(true);
       cmbDevSem.setEnabled(true);
//       rbCompra.setEnabled(true);
 //      rbVenta.setEnabled(true);
       
       ///Habilitar los TEXTFIELD
       txtAccionComercial.setEnabled(true);
       //txtArticulo.setEnabled(true);
      
       txtIdProveedor.setEnabled(true);
       
       //txtRubro.setEnabled(true);
       txtSucursal.setEnabled(true);
        
       txtIdProveedor.requestFocus();///posiciona el cursor
        
         //vacia los campos en ""
        txtIdProveedor.setText("");   
       
        txtIdProveedor.setText("");
        //txtRubro.setText("");
        
        txtSucursal.setText("");
        //txtArticulo.setText(null);
        
    
        this.jcomProveedor.removeAllItems();
        this.jcomMotivo.removeAllItems();

        this.jcomSucursal.removeAllItems();
         
         
        ///Actualizamos los menus
        jcomClaseProveedorMenu();
        jcomClaseCompradorMenu();
        jcomClaseRamos();
        jcomClaseMotivoMenu(1);
        //jcomClaseArticulo();
        jcomClaseSucursal();
        enableDevItems(1);
    }
    private void jcomClaseRamos(){
        jcomRamos.removeAllItems();
       ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        ///ingresamos la consulta
        String sSQL= "SELECT id_ramo,descripcion_ramo FROM ramos order by id_ramo";
        Integer indice=0;
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomRamos.addItem(rs.getString("descripcion_ramo"));
                ramosIdx[indice]=rs.getInt("id_ramo");
                indice+=1;
            }            
                        
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    }
    
    void inhabilitar(){
       
       //Habilitar los botones.
       //btnConsultasPlan.setEnabled(false);
       dpFechaDesde.setEnabled(false);
       dpFechaDesde.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
       dpFechaHasta.setEnabled(false);
       dpFechaHasta.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
       lblListaPrecios.setEnabled(false);
        txtListaPrecios.setEnabled(false);
        txtRamos.setEnabled(false);
        jcomRamos.setEnabled(false);
       //btnNuevoPlan.setEnabled(false);
       //btnSalir.setEnabled(false);
       btnSeleccion.setEnabled(false);
//       rbCompra.setEnabled(false);
 //      rbVenta.setEnabled(false);
       
        ///Habilitar los jCOMBOX
       //jcomArticulo.setEnabled(false);
       
       jcomMotivo.setEnabled(false);
       jcomProveedor.setEnabled(false);

       jcomSucursal.setEnabled(false);
       
       ///Habilitar las etiquetas.
       jlbAccion.setEnabled(false);
       jlbAplicacion.setEnabled(false);
       //jlbArticulo.setEnabled(false);
      
      lblPorcent.setEnabled(false);
       jlbDesde.setEnabled(false);
       jlbHasta.setEnabled(false);
       jlbMotivoSNC.setEnabled(false);
       jlbProveedor.setEnabled(false);

       jlbSucursal.setEnabled(false);
       jlbVigencia.setEnabled(false);
       jlbTitTipoMotSNC.setEnabled(false);
        ///Habilitar Radio botones
       jrbMensual.setEnabled(false);
       jrbSemanal.setEnabled(false);
       lblTitDev.setEnabled(false);
       lblTitDevMes.setEnabled(false);
       lblTitDevSem.setEnabled(false);
       cmbDevMes.setEnabled(false);
       cmbDevSem.setEnabled(false);
        ///Habilitar los TEXTFIELD
        
        txtAccionComercial.setEnabled(false);
        //txtArticulo.setEnabled(false);
       
        txtIdProveedor.setEnabled(false);
        
        //txtRubro.setEnabled(false);
        txtSucursal.setEnabled(false);
        
        ///Habilitar 
        //vacia los campos en ""
        txtIdProveedor.setText("");   
       
        txtIdProveedor.setText("");
        //txtRubro.setText("");
        
       
        txtSucursal.setText("");
        //txtArticulo.setText(null);
        
        
            }
    ////*Clases para actualizar los menús*////
     private void jcomClaseProveedorMenu()
    {
        ///realizamos la conexion con la bdd.
        
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        
        sSQL= "SELECT razon_social FROM proveedor order by 1";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomProveedor.addItem(rs.getString("razon_social"));
                
            }            
                        
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    
    }
     private void jcomClaseCompradorMenu()
    {
       ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        
        sSQL= "select concat (apellido,\" \", nombre) as comprador from usuario where idUsuario='"+UID+"'";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.lblCompName.setText(rs.getString("comprador")); 
                lblCompN.setText(UID);
            }               
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }      
    
    }

    private void jcomClaseMotivoMenu(Integer tipo)
    {
        ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        jcomMotivo.removeAllItems();
        sSQL= "select descripcion from motivo_snc where tipo="+tipo+" order by descripcion";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            jcomMotivo.addItem("");
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomMotivo.addItem(rs.getString("descripcion")); 
            }               
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    }
        
    private void jcomClaseSucursal(){
        
        ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        String idSuc=txtSucursal.getText();
        
        
        sSQL= "select descripcion from sucursal where sucursal.idSucursal like  '%"+idSuc+"%'";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomSucursal.addItem(rs.getString("descripcion")); 
                
            }   
            
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacionBajaPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacionBajaPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacionBajaPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacionBajaPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private String userId;
            public void run() {
                new ModificacionBajaPlan(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultasPlan;
    private javax.swing.JButton btnNuevoPlan;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbDevMes;
    private javax.swing.JComboBox<String> cmbDevSem;
    private org.jdesktop.swingx.JXDatePicker dpFechaDesde;
    private org.jdesktop.swingx.JXDatePicker dpFechaHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JComboBox<String> jcomMotivo;
    private javax.swing.JComboBox<String> jcomProveedor;
    private javax.swing.JComboBox<String> jcomRamos;
    private javax.swing.JComboBox<String> jcomSucursal;
    private javax.swing.JLabel jlbAccion;
    private javax.swing.JLabel jlbAplicacion;
    private javax.swing.JLabel jlbAplicacion1;
    private javax.swing.JLabel jlbDesde;
    private javax.swing.JLabel jlbHasta;
    private javax.swing.JLabel jlbMotivoSNC;
    private javax.swing.JLabel jlbProveedor;
    private javax.swing.JLabel jlbSucursal;
    private javax.swing.JLabel jlbTitTipoMotSNC;
    private javax.swing.JLabel jlbTitTipoMotSNC1;
    private javax.swing.JLabel jlbVigencia;
    private javax.swing.JRadioButton jrbMensual;
    private javax.swing.JRadioButton jrbMensual1;
    private javax.swing.JRadioButton jrbSemanal;
    private javax.swing.JRadioButton jrbSemanal1;
    private javax.swing.JLabel lblCompN;
    private javax.swing.JLabel lblCompName;
    private javax.swing.JLabel lblListaPrecios;
    private javax.swing.JLabel lblPorcent;
    private javax.swing.JLabel lblTitDev;
    private javax.swing.JLabel lblTitDevMes;
    private javax.swing.JLabel lblTitDevSem;
    private javax.swing.JRadioButton rbCompra1;
    private javax.swing.JRadioButton rbCompra2;
    private javax.swing.JRadioButton rbVenta1;
    private javax.swing.JRadioButton rbVenta2;
    private javax.swing.JTextField txtAccionComercial;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtListaPrecios;
    private javax.swing.JLabel txtRamos;
    private javax.swing.JTextField txtSucursal;
    // End of variables declaration//GEN-END:variables
   
}
