/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelos;

import BaseDeDatos.ConexionMySQL;
import BaseDeDatos.conexionSQLServer;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import BackGroundLongTasks.TaskArticulos;
import Reportes.GenerarNC;
import Reportes.GenerarReportes;
import Utils.ExcelUtils;
import java.awt.HeadlessException;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.SAVE_DIALOG;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author usuario
 */
public class NotasCredito extends javax.swing.JFrame {
    /**
     * Creates new form Articulos
     */
    DefaultTableModel modelo; 
       
    public NotasCredito() {
        initComponents();
        String [] titulos= {"Nro de Cierre","Proveedor","Id Plan","Tipo Plan","Motivo SNC", "Importe descuento" };
        
        modelo = new DefaultTableModel(null,titulos);
        tblCierres.setModel(modelo);
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
	Date date = new Date();
        String fechaHoy=dateFormat.format(date);
        loadTable(fechaHoy);
        dpFecha.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        dpFecha.setDate(date);
        
    }
   
    
    private void loadTable(String fechaCierre){
        modelo= (DefaultTableModel) tblCierres.getModel();
        String [] registro= new String[6];
        ///realizamos la conexion con la db
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        //Obtener fecha del cierre de constructor
        String consulta="select id_cierre,prov.razon_social,id_plan_descuento,c.tipo_plan,m.descripcion,fecha_cierre,TRUNCATE (importe_descuento, 2) AS importe_descuento " +
                        "from cierre c, plan_descuento p, motivo_snc m, proveedor prov " +
                        "where c.id_plan_descuento=p.idPlan_Descuento " +
                        "and p.Motivo_SNC_idMotivo_SNC=m.idMotivo_SNC " +
                        "and prov.idproveedor=p.Proveedor_idproveedor " +
                        "and date_format(c.fecha_cierre,'%Y-%m-%d')='"+fechaCierre+"';";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(consulta);
            //ASIGNACION DE LOS CAMPOS A LOS REGISTROS DE LA TABLA
            while (rs.next())
            {
                registro[0]=rs.getString("id_cierre");
                registro[1]=rs.getString("razon_social");
                registro[2]=rs.getString("id_plan_descuento");
                registro[3]=rs.getString("tipo_plan");
                registro[4]=rs.getString("Descripcion");
                registro[5]=rs.getString("importe_descuento");
                modelo.addRow(registro);
              }
            //tblCierres.setModel(modelo);               
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
   
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnEditar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dpFecha = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCierres = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);

        mnEditar.setText("Mostrar Nota de Crédito");
        mnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnEditar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Potigian- Notas de Crédito", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Seleccionar Fecha Cierre:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel7.setText("Visualizar notas de Crédito Generadas");

        dpFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpFechaActionPerformed(evt);
            }
        });

        tblCierres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCierres.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(tblCierres);

        jButton1.setText("Exportar a Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(dpFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Potigian- Actualizacion De Artículos");

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    
    
    private void mnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditarActionPerformed
        int filasel;
        int idpl=0;
        String idString="";
        GenerarNC repNC= new GenerarNC(); 
        modelo= (DefaultTableModel) tblCierres.getModel();
        try
           {
               filasel=tblCierres.getSelectedRow();
               if (filasel==-1)
               {
                     JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila");
               }else{
                   idString= (String)modelo.getValueAt(filasel, 0);
                   String tp = (String)modelo.getValueAt(filasel, 3);
                   if (tp.equals("FIJO")){
                        idpl= Integer.valueOf(idString);
                        repNC.reporteNCF(idpl);
                   }else{
                        idpl= Integer.valueOf(idString);
                        repNC.reporteNC(idpl);
                   }
               }     
           }
        catch (HeadlessException | NumberFormatException e){
           }
    }//GEN-LAST:event_mnEditarActionPerformed

    private void dpFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpFechaActionPerformed
        // TODO add your handling code here:
        ((DefaultTableModel) tblCierres.getModel()).setRowCount(0);
        loadTable(new SimpleDateFormat("yyyy-MM-dd").format(dpFecha.getDate()));
    }//GEN-LAST:event_dpFechaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<String> headers = new ArrayList<>();
        List<List<String>> content = new ArrayList<>();
        
        JFileChooser chooser = new JFileChooser()
        {
            @Override
            public void approveSelection() {
                File f = getSelectedFile();
                if (f.exists() && getDialogType() == SAVE_DIALOG) {
                    int result = JOptionPane.showConfirmDialog(this,
                            "El archivo ya existe, ¿desea sobreescribir?", "Archivo ya existente",
                            JOptionPane.YES_NO_CANCEL_OPTION);
                    switch (result) {
                    case JOptionPane.YES_OPTION:
                        super.approveSelection();
                        return;
                    case JOptionPane.CANCEL_OPTION:
                        cancelSelection();
                        return;
                    default:
                        return;
                    }
                }
                super.approveSelection();
            }
        };
        chooser.setFileFilter(new FileNameExtensionFilter("Archivo XLS", "xls", "excel"));
        chooser.setSelectedFile(new File("notas_credito.xls"));
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            File dest = chooser.getSelectedFile();
            
            for (int i = 0; i < tblCierres.getColumnCount(); i++)
                headers.add(tblCierres.getColumnName(i));
        
            for (int i = 0; i < tblCierres.getRowCount(); i++)
            {
                List<String> rowContent = new ArrayList<>();
                for (int j = 0; j < tblCierres.getColumnCount(); j++)
                    rowContent.add((String) tblCierres.getValueAt(i, j));
                content.add(rowContent);
            }
            
            try
            {
                ExcelUtils.exportToExcel(dest, headers, content, "Planes Fijos");
                JOptionPane.showMessageDialog(this, "Archivo creado exitosamente",
                        "Creación OK", JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this, "Hubo un error al intentar exportar: \n" +
                        e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void refreshAP(){
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        //PREPARO CONSULTA PARA OBTENER FECHA
       
        String queryAP="truncate table articulo_proveedor";
        //OBTENGO FECHA Y LA CARGO EN EL LABEL
        try {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(queryAP);
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Articulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Articulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private org.jdesktop.swingx.JXDatePicker dpFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnEditar;
    private javax.swing.JTable tblCierres;
    // End of variables declaration//GEN-END:variables
}
