/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelos;

import BaseDeDatos.ConexionMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author usuario
 */


public class PendienteDeCarga extends javax.swing.JFrame {

    /**
     * Creates new form PendienteDeCarga
     */
    private String UID;
      
    public PendienteDeCarga(String userId) {
        initComponents();
        UID=userId;
             habilitar();
        System.out.println("userID: "+userId);
        
         txtMotivoSNC.setText("");
       prepcmbDevs();
        
        inhabilitar();
        txtMotivoSNC.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void removeUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void insertUpdate(DocumentEvent e) {
              updateCombo();
            }

            public void updateCombo() {
                ConexionMySQL mysql= new ConexionMySQL();
                Connection cn= mysql.Conectar();

                String sSQL="", idMotiv="";
                idMotiv= txtMotivoSNC.getText();

                sSQL= "select descripcion from motivo_snc where idmotivo_snc = '"+idMotiv+"'  and tipo=0";
                
                System.out.println("1"+ sSQL);

                try
                {
                    Statement st= cn.createStatement();
                    ResultSet rs= st.executeQuery(sSQL);
                    if (rs.next())
                        try {
                            jcomMotivo.setSelectedItem(rs.getString("descripcion")); 
                        } catch (IllegalStateException e) {}
                    else
                        jcomMotivo.setSelectedItem(null);
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
        txtIdProveedor.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void removeUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void insertUpdate(DocumentEvent e) {
              updateCombo();
            }

            public void updateCombo() {
                ConexionMySQL mysql= new ConexionMySQL();
                Connection cn= mysql.Conectar();

                String sSQL="", idProv="";
                idProv= txtIdProveedor.getText();

                sSQL = "select pr.razon_social as razon from proveedor as pr where pr.idproveedor = '"+idProv+"'";

                try
                {
                    Statement st= cn.createStatement();
                    ResultSet rs= st.executeQuery(sSQL);
                    if (rs.next())
                    {
                        try {
                            jcomProveedor.setSelectedItem(rs.getString("razon")); 
                        } catch (IllegalStateException e) {}
                    }
                    else
                        jcomProveedor.setSelectedItem(null);
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        jlbMotivoSNC = new javax.swing.JLabel();
        txtMotivoSNC = new javax.swing.JTextField();
        jcomMotivo = new javax.swing.JComboBox<>();
        jlbProveedor = new javax.swing.JLabel();
        txtIdProveedor = new javax.swing.JTextField();
        jcomProveedor = new javax.swing.JComboBox<>();
        lblVigencia = new javax.swing.JLabel();
        lblFInicio = new javax.swing.JLabel();
        dpFInicio = new org.jdesktop.swingx.JXDatePicker();
        lblFFin = new javax.swing.JLabel();
        dpFFin = new org.jdesktop.swingx.JXDatePicker();
        jPanel3 = new javax.swing.JPanel();
        lblTitDev = new javax.swing.JLabel();
        lblTitDevMes = new javax.swing.JLabel();
        cmbDevMes = new javax.swing.JComboBox<>();
        jlbObsProveedor = new javax.swing.JLabel();
        txtObsProveedor = new javax.swing.JTextField();
        jlbObsComprador = new javax.swing.JLabel();
        txtObsComprador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblCompN = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCompName = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PLAN ESPECIAL");

        btnNuevo.setText("Nuevo Plan");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnConsulta.setText("Consultas");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        jlbMotivoSNC.setText("Motivo SNC:");

        jcomMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcomMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomMotivoActionPerformed(evt);
            }
        });

        jlbProveedor.setBackground(new java.awt.Color(51, 204, 0));
        jlbProveedor.setText("Proveedor:");

        jcomProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcomProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomProveedorActionPerformed(evt);
            }
        });

        lblVigencia.setText("Vigencia del Plan:");

        lblFInicio.setText("Fecha Inicio:");

        lblFFin.setText("Fecha Fin:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitDev.setText("Devengamiento:");

        lblTitDevMes.setText("Dia del Mes:");

        cmbDevMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitDevMes)
                            .addComponent(cmbDevMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitDev))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTitDev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitDevMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDevMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jlbObsProveedor.setText("Obs. Proveedor:");

        txtObsProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObsProveedorActionPerformed(evt);
            }
        });

        jlbObsComprador.setText("Obs. Comprador: ACUERDO ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Comprador:");

        lblCompN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCompN.setText("[N]");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("-");

        lblCompName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCompName.setText("[COMP_NAME]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)
                                .addComponent(lblCompN)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2)
                                .addGap(15, 15, 15)
                                .addComponent(lblCompName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblVigencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbMotivoSNC)
                                            .addComponent(jlbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtMotivoSNC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jcomMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jcomProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblFInicio)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dpFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(lblFFin)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dpFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jlbObsProveedor))
                                        .addGap(37, 37, 37)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 146, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbObsComprador)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtObsComprador, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObsProveedor))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(lblCompN)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCompName))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevo)
                        .addComponent(btnConsulta)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMotivoSNC)
                    .addComponent(txtMotivoSNC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbProveedor)
                    .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVigencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFInicio)
                            .addComponent(dpFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFFin)
                            .addComponent(dpFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbObsProveedor))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObsProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbObsComprador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObsComprador, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       habilitar();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jcomMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomMotivoActionPerformed
        ///realizamos la conexion con la bdd.

        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();

        ///ingresamos la consulta
        String sSQL="", motivo="";
        motivo=(String) jcomMotivo.getSelectedItem();

        sSQL= "select idmotivo_snc as id from motivo_snc where descripcion LIKE '%"+motivo+"%' and tipo=0";
        
        System.out.println("2"+sSQL);

        try
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);

            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                if (!jcomMotivo.getSelectedItem().toString().equals("")){
                    try {
                        txtMotivoSNC.setText(rs.getString("id"));
                    } catch (IllegalStateException e) {}
                }else{
                    txtMotivoSNC.setText("");
                }
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jcomMotivoActionPerformed

    private void jcomProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomProveedorActionPerformed
        ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        ///ingresamos la consulta
        String sSQL="", razon="";
        razon=(String) jcomProveedor.getSelectedItem();

        sSQL= "select pr.idproveedor as id from proveedor as pr where pr.razon_social LIKE '%"+razon+"%'";

        try
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);

            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                if(!jcomProveedor.getSelectedItem().toString().equals("")){
                    try {
                        txtIdProveedor.setText(rs.getString("id"));
                    } catch (IllegalStateException e) {}
                }else{
                    txtIdProveedor.setText("");
                }
                //this.jcomArticulo.removeAllItems();
                //jcomClaseArticulo();

            }
            //jcomProveedor.transferFocus();
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jcomProveedorActionPerformed
  private void jcomClaseCompradorMenu()
    {
       ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        
        sSQL= "select concat (apellido,\" \", nombre) as comprador from usuario where idUsuario='"+UID+"'";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                //this.jcomComprador.addItem(rs.getString("comprador")); 
                lblCompName.setText(rs.getString("comprador"));
                lblCompN.setText(UID);
            }               
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }      
    
    }
   private void jcomClaseProveedorMenu()
    {
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        String sSQL="";
        sSQL= "SELECT razon_social FROM proveedor order by 1";
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            jcomProveedor.addItem("");
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomProveedor.addItem(rs.getString("razon_social"));   
            }               
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    }
   
   private void jcomClaseMotivoMenu()
    {
        ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        
        sSQL= "select descripcion from motivo_snc where tipo=0";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            jcomMotivo.addItem("");
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomMotivo.addItem(rs.getString("descripcion")); 
            }               
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    }
   
   
       private void prepcmbDevs(){
        cmbDevMes.removeAllItems();
        for(Integer cont=1;cont<=31;cont++){
            cmbDevMes.addItem(cont.toString());
        }
    } 
       
       
  
  
  /////////////////////////////////////////////////////////////////////////////
    //////////////CLASES PARA HABILITAR E INHABILITAR LOS MENUS//////////////////
    /////////////////////////////////////////////////////////////////////////////
    
    void habilitar()
    {
   //habilita cada opción
        
    /// CAMPOS DE TEXTO Y ETIQUETAS  
    lblVigencia.setEnabled(true);
    lblFInicio.setEnabled(true);
    lblFFin.setEnabled(true);
    dpFInicio.setEnabled(true);
    dpFFin.setEnabled(true);
    txtIdProveedor.setEnabled(true);
    lblTitDev.setEnabled(true);
    lblTitDevMes.setEnabled(true);
    cmbDevMes.setEnabled(true);
    jcomProveedor.setEnabled(true);
    jlbProveedor.setEnabled(true);

    txtIdProveedor.setEnabled(true);
    jcomProveedor.setEnabled(true);
    jlbProveedor.setEnabled(true);
 
    txtMotivoSNC.setEnabled(true);
    jcomMotivo.setEnabled(true);
    jlbMotivoSNC.setEnabled(true);
    txtObsProveedor.setEnabled(true);
    jlbObsProveedor.setEnabled(true);
    txtObsComprador.setEnabled(true);
    jlbObsComprador.setEnabled(true);
    cmbDevMes.setEnabled(true);
    
    ///BOTONES Y ACCIONES
    btnNuevo.setEnabled(true);
    btnConsulta.setEnabled(true);
    btnConfirmar.setEnabled(true);

    
    txtIdProveedor.requestFocus();///posiciona el cursor
    
    this.jcomProveedor.removeAllItems();

    this.jcomMotivo.removeAllItems();

    
     //vacia los campos en ""
    txtIdProveedor.setText("");   

    txtIdProveedor.setText("");
    
    txtMotivoSNC.setText("");
    txtObsProveedor.setText("");
    txtObsComprador.setText("");

  
    jcomClaseProveedorMenu();
    jcomClaseCompradorMenu();
    
    jcomClaseMotivoMenu();
  
    
    
    }
    ///metodo para cancelar la carga de datos
   
    void inhabilitar(){
    //deshabilita cada opción
    
    ///CAMPOS DE TEXTOS Y ETIQUETAS
    lblVigencia.setEnabled(false);
    lblFInicio.setEnabled(false);
    lblFFin.setEnabled(false);
    dpFInicio.setEnabled(false);
    dpFFin.setEnabled(false);
  
    lblTitDev.setEnabled(false);
    lblTitDevMes.setEnabled(false);
    cmbDevMes.setEnabled(false);
    txtIdProveedor.setEnabled(false);
    jcomProveedor.setEnabled(false);
    jlbProveedor.setEnabled(false);
    txtMotivoSNC.setEnabled(false);
    jcomMotivo.setEnabled(false);
    jlbMotivoSNC.setEnabled(false);
    txtObsProveedor.setEnabled(false);
    jlbObsProveedor.setEnabled(false);
    txtObsComprador.setEnabled(false);
    jlbObsComprador.setEnabled(false);
    cmbDevMes.setEnabled(false);

    ///BOTONES
    btnNuevo.setEnabled(true);
    btnConsulta.setEnabled(true);
    btnConfirmar.setEnabled(false);
    
    this.jcomProveedor.removeAllItems();
    this.jcomMotivo.removeAllItems();
 
    txtIdProveedor.setText("");   
    txtIdProveedor.setText("");
   
    txtMotivoSNC.setText("");
    txtObsProveedor.setText("");
    txtObsComprador.setText("");
   
    }
    
    
    
    private void txtObsProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObsProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObsProveedorActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        PendienteDeCarga.this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
    String accion="Insertar";
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
         //conexión a la bdd
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        ///FECHA ACTUAL
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
        String mensaje,fechaInicio,fechaFin, fecha, sSQL;
        fecha = sdf.format(date);
        ///STRING A UTILIZAR
        String idProve="", tipoDePlan="",fechaActual="",importe="0", cuotas="0", idComprador="",idSector="";
        String motivoSNC="",descuento="0", descDescripcion="", obsComprador="", obsProveedor="",tipoIVA="0", idArt="0";
      // cantCopias="0"
        sSQL="";
        fechaInicio=null;
        fechaFin=null;
       ///campos a cargar
        if(dpFInicio.getDate()!=null){
            fechaInicio = sdf.format(dpFInicio.getDate());
        }else{
            fechaInicio = fecha;
        }
        if(dpFFin.getDate()!=null){
            fechaFin = sdf.format(dpFFin.getDate());
        }
        idProve=txtIdProveedor.getText();
        tipoDePlan="PENDIENTE";
        String estado="ACTIVO";
        String situacion="PENDIENTE";
        
        //System.out.println("FECHA" + fecha);
        fechaActual= fecha;
       // importe=txtImporte.getText();
      //  cuotas=ComboCuotas.getSelectedItem().toString();
        idComprador= lblCompN.getText();
        //idComprador= txtComprador.getText();
        //idSector=txtSector.getText();
        //idSector="0";
        motivoSNC= txtMotivoSNC.getText();        
        obsProveedor= txtObsProveedor.getText();
        obsComprador=txtObsComprador.getText();
      //  tipoIVA=getIVA();
        ///verifico que no se envie un articulo no elegido
  /*      if (this.jCheckArticulo.isSelected()==true){
             idArt=null;}
        else {
            idArt=null;
        }
        //cantCopias=txtCantCopias.getText ();
        
        */
        ///creamos la consulta sql
        if (accion.equals("Insertar"))
        {
            sSQL="INSERT INTO plan_descuento (Proveedor_idproveedor, tipo_plan,aplicacion,dia_devengamiento,fechaActual,"
                    + " fecha_devengamiento_Desde,fecha_Devengamiento_Hasta, Usuario_idusuario,Motivo_SNC_idMotivo_SNC,"
                    + "obs_Proveedor, obs_Comprador,estado,situacion) "+
                "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
           mensaje="Operación Satisfactoria";
        }
        /*
        else if (accion.equals("Modificar"))
        {
            sSQL="UPDATE articulo " +
                 "SET idArticulo= ?," +
                 "descripcion= ?, "+
                 "unidad_de_venta= ?, " +
                 "fecha_ingreso_inicial= ?, " +
                 "precio_costo= ? ," +
                 "precio_vigente= ? ," +
                 "margen=?," +   
                 "proveedor_idproveedor= ? , "+
                 "cantidad_total= ? " +  
                 "WHERE idArticulo= " + id_actualizar;
            mensaje="Operación Satisfactoría";
        }
        */
        
        try 
        {
            PreparedStatement pst= cn.prepareStatement(sSQL);
            pst.setString(1, idProve );
            pst.setString(2, tipoDePlan);
            pst.setString(3, "Mensual");
            pst.setString(4, cmbDevMes.getSelectedItem().toString());
            pst.setString(5, fechaActual);  
            pst.setString(6, fechaInicio);
            pst.setString(7, fechaFin);
            pst.setString(8, idComprador);
            pst.setString(9, motivoSNC);
            pst.setString(10,obsProveedor);
            pst.setString(11,obsComprador);
            pst.setString(12,situacion);
            pst.setString(13,estado);
            int n = pst.executeUpdate();
          //  guardarCuotas(cn);
            if (n>0)
            {    
                mensaje="Operación Satisfactoria";
                
                JOptionPane.showMessageDialog(null, mensaje);
               // CargarTablaCuotas("");
                habilitar();//habilita los campos para la carga de datos
                inhabilitar();
                ConsultaPendientes ventanaConsulta= new ConsultaPendientes();
                ventanaConsulta.setExtendedState(JFrame.MAXIMIZED_BOTH);
                ventanaConsulta.setVisible(true);
           
            }
            
        } 
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        ConsultaPendientes ventanaConsulta= new ConsultaPendientes();
        ventanaConsulta.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ventanaConsulta.setVisible(true);
    }//GEN-LAST:event_btnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendienteDeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendienteDeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendienteDeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendienteDeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             private String userId;
            public void run() {
                new PendienteDeCarga(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbDevMes;
    private org.jdesktop.swingx.JXDatePicker dpFFin;
    private org.jdesktop.swingx.JXDatePicker dpFInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcomMotivo;
    private javax.swing.JComboBox<String> jcomProveedor;
    private javax.swing.JLabel jlbMotivoSNC;
    private javax.swing.JLabel jlbObsComprador;
    private javax.swing.JLabel jlbObsProveedor;
    private javax.swing.JLabel jlbProveedor;
    private javax.swing.JLabel lblCompN;
    private javax.swing.JLabel lblCompName;
    private javax.swing.JLabel lblFFin;
    private javax.swing.JLabel lblFInicio;
    private javax.swing.JLabel lblTitDev;
    private javax.swing.JLabel lblTitDevMes;
    private javax.swing.JLabel lblVigencia;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtMotivoSNC;
    private javax.swing.JTextField txtObsComprador;
    private javax.swing.JTextField txtObsProveedor;
    // End of variables declaration//GEN-END:variables
}
