/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelos;

import BaseDeDatos.ConexionMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author usuario
 */
public class PlanVariableSinDev extends javax.swing.JFrame {

    /**
     * Creates new form PlanVariable
     */
    private String UID;
    private String motivo_sncS;
    private String rubroS="0";
    private Integer ramosSelected=0;
    int[] ramosIdx = new int[100];
    private List<String> listaArticulos=new ArrayList<String>();;
    
    public PlanVariableSinDev(String userId) {
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
        UID=userId;
        initComponents();
        prepcmbDevs();
        habilitar();
        inhabilitar();
        
        txtSucursal.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void removeUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void insertUpdate(DocumentEvent e) {
              updateCombo();
            }

            public void updateCombo() {
                ConexionMySQL mysql= new ConexionMySQL();
                Connection cn= mysql.Conectar();

                String sSQL="", idSuc="";
                idSuc= txtSucursal.getText();

                sSQL= "select descripcion from sucursal where idSucursal = '"+idSuc+"'";

                try
                {
                    Statement st= cn.createStatement();
                    ResultSet rs= st.executeQuery(sSQL);
                    if (rs.next())
                        try {
                            jcomSucursal.setSelectedItem(rs.getString("descripcion")); 
                        } catch (IllegalStateException e) {}
                    else
                        jcomSucursal.setSelectedItem(null);
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
        txtIdProveedor.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void removeUpdate(DocumentEvent e) {
              updateCombo();
            }
            public void insertUpdate(DocumentEvent e) {
              updateCombo();
            }

            public void updateCombo() {
                ConexionMySQL mysql= new ConexionMySQL();
                Connection cn= mysql.Conectar();

                String sSQL="", idProv="";
                idProv= txtIdProveedor.getText();

                sSQL= "select pr.razon_social as razon from proveedor as pr where pr.idproveedor = '"+idProv+"'";

                try
                {
                    Statement st= cn.createStatement();
                    ResultSet rs= st.executeQuery(sSQL);
                    if (rs.next())
                        try {
                            jcomProveedor.setSelectedItem(rs.getString("razon")); 
                        } catch (IllegalStateException e) {}
                    else
                        jcomProveedor.setSelectedItem(null);
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btnGrpTipoPlan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jlbProveedor = new javax.swing.JLabel();
        txtIdProveedor = new javax.swing.JTextField();
        jlbMotivoSNC = new javax.swing.JLabel();
        btnNuevoPlan = new javax.swing.JButton();
        btnConsultasPlan = new javax.swing.JButton();
        jcomProveedor = new javax.swing.JComboBox<>();
        jcomMotivo = new javax.swing.JComboBox<>();
        jlbVigencia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlbAplicacion = new javax.swing.JLabel();
        jrbMensual = new javax.swing.JRadioButton();
        jrbSemanal = new javax.swing.JRadioButton();
        btnSeleccion = new javax.swing.JButton();
        jlbAccion = new javax.swing.JLabel();
        txtAccionComercial = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        jlbDesde = new javax.swing.JLabel();
        jlbHasta = new javax.swing.JLabel();
        dpFechaHasta = new org.jdesktop.swingx.JXDatePicker();
        dpFechaDesde = new org.jdesktop.swingx.JXDatePicker();
        lblPorcent = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTitDev = new javax.swing.JLabel();
        lblTitDevMes = new javax.swing.JLabel();
        cmbDevMes = new javax.swing.JComboBox<>();
        lblTitDevSem = new javax.swing.JLabel();
        cmbDevSem = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jlbTitTipoMotSNC = new javax.swing.JLabel();
        rbCompra = new javax.swing.JRadioButton();
        rbVenta = new javax.swing.JRadioButton();
        lblCompN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCompName = new javax.swing.JLabel();
        lblListaPrecios = new javax.swing.JLabel();
        txtListaPrecios = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jlbSucursal = new javax.swing.JLabel();
        txtSucursal = new javax.swing.JTextField();
        jcomSucursal = new javax.swing.JComboBox<>();
        txtRamos = new javax.swing.JLabel();
        jcomRamos = new javax.swing.JComboBox<>();
        jlbObsProveedor = new javax.swing.JLabel();
        txtObsProveedor = new javax.swing.JTextField();
        jlbObsComprador = new javax.swing.JLabel();
        txtObsComprador = new javax.swing.JTextField();
        txtModoCancelacion = new javax.swing.JLabel();
        cmbModoCancelacion = new javax.swing.JComboBox<>();
        txtModoImpacto = new javax.swing.JLabel();
        cmbImpacto = new javax.swing.JComboBox<>();
        txtCanal = new javax.swing.JLabel();
        cmbCanal = new javax.swing.JComboBox<>();
        jBaceptar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setTitle("PLAN IMPORTE VARIABLE");
        setSize(new java.awt.Dimension(1366, 768));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Condiciones del Plan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbProveedor.setBackground(new java.awt.Color(51, 204, 0));
        jlbProveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbProveedor.setText("Proveedor:");
        jlbProveedor.setMaximumSize(new java.awt.Dimension(60, 14));
        jlbProveedor.setMinimumSize(new java.awt.Dimension(60, 14));
        jlbProveedor.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jlbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 20));

        txtIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 62, -1));

        jlbMotivoSNC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbMotivoSNC.setText("Motivo SNC:");
        jlbMotivoSNC.setMaximumSize(new java.awt.Dimension(60, 14));
        jlbMotivoSNC.setMinimumSize(new java.awt.Dimension(60, 14));
        jlbMotivoSNC.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel1.add(jlbMotivoSNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 905, -1));

        btnNuevoPlan.setText("Nuevo Plan");
        btnNuevoPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPlanActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 115, 32));

        btnConsultasPlan.setText("Consultas");
        btnConsultasPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasPlanActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultasPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 117, 32));

        jcomProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(jcomProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 990, -1));

        jcomMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomMotivoActionPerformed(evt);
            }
        });
        jPanel1.add(jcomMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 990, -1));

        jlbVigencia.setText("Vigencia Devengamiento:");
        jPanel1.add(jlbVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 154, 23));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbAplicacion.setText("Aplicación:");

        jrbMensual.setText("Mensual");
        jrbMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMensualActionPerformed(evt);
            }
        });

        jrbSemanal.setText("Semanal");
        jrbSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSemanalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbSemanal)
                    .addComponent(jlbAplicacion)
                    .addComponent(jrbMensual))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jlbAplicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMensual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbSemanal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        btnSeleccion.setText("Seleccionar Articulos");
        btnSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 160, 40));

        jlbAccion.setText("Acción Comercial: ");
        jPanel1.add(jlbAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 425, 118, -1));

        txtAccionComercial.setText("0");
        txtAccionComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccionComercialActionPerformed(evt);
            }
        });
        jPanel1.add(txtAccionComercial, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 87, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 110, 40));

        jlbDesde.setText("Desde");
        jPanel1.add(jlbDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jlbHasta.setText("Hasta");
        jPanel1.add(jlbHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));
        jPanel1.add(dpFechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 140, -1));
        jPanel1.add(dpFechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 140, -1));

        lblPorcent.setText("%");
        jPanel1.add(lblPorcent, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 425, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTitDev.setText("Devengamiento:");

        lblTitDevMes.setText("Dia del Mes:");

        cmbDevMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTitDevSem.setText("Dia de la Semana:");

        cmbDevSem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitDevMes)
                            .addComponent(cmbDevMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitDevSem)
                            .addComponent(cmbDevSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitDev))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTitDev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitDevMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDevMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitDevSem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDevSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlbTitTipoMotSNC.setText("Tipo de Motivo SNC:");

        rbCompra.setText("Compra");
        rbCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCompraActionPerformed(evt);
            }
        });

        rbVenta.setText("Venta");
        rbVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jlbTitTipoMotSNC)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rbCompra)
                .addGap(18, 18, 18)
                .addComponent(rbVenta)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jlbTitTipoMotSNC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCompra)
                    .addComponent(rbVenta))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 160, -1));

        lblCompN.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCompN.setText("[N]");
        jPanel1.add(lblCompN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Comprador:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 20, -1, 19));

        lblCompName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCompName.setText("[COMP_NAME]");
        jPanel1.add(lblCompName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 164, -1));

        lblListaPrecios.setText("Lista de precios:");
        jPanel1.add(lblListaPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 225, -1, -1));
        jPanel1.add(txtListaPrecios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, -1));

        jlbSucursal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbSucursal.setText("Sucursal:");
        jlbSucursal.setMaximumSize(new java.awt.Dimension(60, 14));
        jlbSucursal.setMinimumSize(new java.awt.Dimension(60, 14));
        jlbSucursal.setPreferredSize(new java.awt.Dimension(60, 14));

        jcomSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jlbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcomSucursal, 0, 991, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jcomSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 1170, 40));

        txtRamos.setText("Ramos:");
        jPanel1.add(txtRamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jcomRamos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcomRamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomRamosActionPerformed(evt);
            }
        });
        jPanel1.add(jcomRamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 380, -1));

        jlbObsProveedor.setText("Obs. Proveedor:");
        jPanel1.add(jlbObsProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        txtObsProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtObsProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(txtObsProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 660, 20));

        jlbObsComprador.setText("Obs. Comprador: ");
        jPanel1.add(jlbObsComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, -1));
        jPanel1.add(txtObsComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 660, 30));

        txtModoCancelacion.setText("Modo de Cancelación");
        jPanel1.add(txtModoCancelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, -1, -1));

        cmbModoCancelacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbModoCancelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbModoCancelacionActionPerformed(evt);
            }
        });
        jPanel1.add(cmbModoCancelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 330, 260, -1));

        txtModoImpacto.setText("Modo de Impacto");
        jPanel1.add(txtModoImpacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, -1, -1));

        cmbImpacto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbImpacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImpactoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbImpacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, 260, -1));

        txtCanal.setText("Canal");
        jPanel1.add(txtCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, -1, -1));

        cmbCanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCanalActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 260, -1));

        jBaceptar.setText("Confirmar");
        jBaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jBaceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        PlanVariableSinDev.this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtAccionComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccionComercialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccionComercialActionPerformed

    
    
    
    ///clase para guardar los articulos
    
    private void aceptar() {
        
        int index= 0;
        String articulo="";
        //conexión a la bdd
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        //STRING A UTILIZAR
        String ultimoId="", idArt="";
        String sSQL="",sSQLid="";
        String mensaje;

        ////Guardamos consulta para ultimo id.
        sSQLid="SELECT LAST_INSERT_ID(idPlan_Descuento) AS ProximoIdAInsertar FROM plan_descuento ORDER BY idPlan_Descuento DESC LIMIT 1";
        ///Guardamos la consulta para insertar el dato
        sSQL="INSERT INTO plan_articulo (idPlan_Descuento, idArticulo) " +
        "VALUES (?,?)";
        mensaje="Operación Satisfactoria";

        ///ARRANCA

        try
        {
            PreparedStatement pst= cn.prepareStatement(sSQLid);
            ResultSet resultado= pst.executeQuery();
            while (resultado.next()) { //Es mas correcto poner el next en el while, te hace lo mismo que tenias en tu antiguo codigo pero en menos lineas y mas limpio
                ultimoId = resultado.getString("ProximoIdAInsertar");
            }
            System.out.println(ultimoId);

            ///obtenemos longitud de los elementos seleccionados.
            index=listaArticulos.size();
            System.out.println(index);
            for (int i=0; i< index; i++ ){

               idArt= listaArticulos.get(i);
              
               PreparedStatement pst2= cn.prepareStatement(sSQL);
                pst2.setString(1, ultimoId);
                pst2.setString(2, idArt);
                pst2.executeUpdate();

            }
            JOptionPane.showMessageDialog(null, mensaje);
            
         
            System.out.println(listaArticulos);

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
        this.setVisible(false);
    }
    private void confirmarOP(){
         if (dpFechaDesde.getDate()==null ||dpFechaHasta.getDate()==null){
            String mensaje="Verificar fechas!!!";
            JOptionPane.showMessageDialog(null, mensaje);
        }else{
            //conexión a la bdd
            ConexionMySQL mysql= new ConexionMySQL();
            Connection cn= mysql.Conectar();
            ///FECHA ACTUAL
            java.util.Date date = new java.util.Date();
            java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(date);
            ///STRING A UTILIZAR
            String idProve="", tipoDePlan="",fechaActual="", sucursal="0", idComprador="",idRubro="";
            String motivoSNC="", idArt="0", fechaDesde="", fechaHasta="";
            String accionComercial="", tipoDeAplicacion="", obsComprador="", obsProveedor="";
            String listaPre="", mCancelacion="", mImpacto="", mCanal="";
            if (txtListaPrecios.getText().equals("")){
                listaPre="TODAS";
            }else{
                listaPre=txtListaPrecios.getText();
            }
            // cantCopias="0"
            String sSQL="";
            String mensaje;
            String estado="PENDIENTE";
            String situacion="ACTIVO";
            ///campos a cargar
            idProve= txtIdProveedor.getText();
            tipoDePlan= "VARIABLE";
            fechaActual= fecha;
            idComprador= lblCompN.getText();
            sucursal= txtSucursal.getText();
            idRubro= ramosSelected.toString();
            motivoSNC= motivo_sncS;
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            fechaDesde= sdf1.format(dpFechaDesde.getDate()).toString();
            fechaHasta= sdf1.format(dpFechaHasta.getDate()).toString();
            accionComercial=txtAccionComercial.getText();
            obsProveedor= txtObsProveedor.getText();
            obsComprador=txtObsComprador.getText();
            mCancelacion=cmbModoCancelacion.getSelectedItem().toString();
            mImpacto=cmbImpacto.getSelectedItem().toString();
            mCanal=cmbCanal.getSelectedItem().toString();
            

            if (this.jrbMensual.isSelected()==true){
                tipoDeAplicacion="Mensual";
            }
            else{
                if (this.jrbSemanal.isSelected()==true){
                    tipoDeAplicacion="Semanal";}
            }
            idArt=null;
            //SETEAMOS EL DIA DE DEVENGAMIENTO
            Integer diaDev = setDiaDevengamiento();
            ///creamos la consulta sql
            if (accion.equals("Insertar"))
            {
                sSQL="INSERT INTO plan_descuento (Proveedor_idproveedor, tipo_plan,fechaActual,"
                + "Usuario_idusuario,Sucursal_idSucursal,Sector_idsector,Motivo_SNC_idMotivo_SNC,"
                + "fecha_Devengamiento_Desde, fecha_Devengamiento_Hasta, accion_comercial,"
                + " aplicacion,dia_devengamiento,Articulo_idArticulo,lista_precio,estado,situacion,"
                + " obs_Proveedor, obs_Comprador, "
                + " Modo_Cancelacion ,Modo_Impacto, Modo_Canal) "  
                +"VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                
                mensaje="Operación Satisfactoria";
            }
            try
            {
                PreparedStatement pst= cn.prepareStatement(sSQL);
                pst.setString(1, idProve );
                pst.setString(2, tipoDePlan);
                pst.setString(3, fechaActual);
                pst.setString(4, idComprador);
                pst.setString(5, sucursal);
                pst.setString(6, idRubro);
                pst.setString(7, motivoSNC);
                pst.setString(8, fechaDesde);
                pst.setString(9, fechaHasta);
                pst.setString(10,accionComercial);
                pst.setString(11,tipoDeAplicacion);
                pst.setString(12,diaDev.toString());
                pst.setString(13,idArt);
                pst.setString(14,listaPre);
                pst.setString(15,estado);
                pst.setString(16,situacion);
                pst.setString(17,obsProveedor);
                pst.setString(18,obsComprador);
                pst.setString(19,mCancelacion);
                pst.setString(20,mImpacto);
                pst.setString(21,mCanal);

                int n = pst.executeUpdate();

                if (n>0)
                {
                    mensaje="Operación Satisfactoria";

                    JOptionPane.showMessageDialog(null, mensaje);
                    
                    

                    habilitar();//habilita los campos para la carga de datos
                    inhabilitar();
                    
                      aceptar();
                   // SeleccionArticulosVariablesArray ventanaArticulos= new SeleccionArticulosVariablesArray(idProve,listaArticulos);
                    //ventanaArticulos.setExtendedState(JFrame.MAXIMIZED_BOTH);
                 //   ventanaArticulos.setVisible(true);
                    resetFormControls();
                  
                }

            }

            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
       
        
    }
    
    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
        if (dpFechaDesde.getDate()==null ||dpFechaHasta.getDate()==null){
            String mensaje="Verificar fechas!!!";
            JOptionPane.showMessageDialog(null, mensaje);
        }else{
            //conexión a la bdd
            ConexionMySQL mysql= new ConexionMySQL();
            Connection cn= mysql.Conectar();
            ///FECHA ACTUAL
            java.util.Date date = new java.util.Date();
            java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("yyyy-MM-dd");
            String fecha = sdf.format(date);
            ///STRING A UTILIZAR
            String idProve="", tipoDePlan="",fechaActual="", sucursal="0", idComprador="",idRubro="";
            String motivoSNC="", idArt="0", fechaDesde="", fechaHasta="";
            String accionComercial="", tipoDeAplicacion="", obsComprador="", obsProveedor="";
            String listaPre="", mCancelacion="", mImpacto="", mCanal="";
            if (txtListaPrecios.getText().equals("")){
                listaPre="TODAS";
            }else{
                listaPre=txtListaPrecios.getText();
            }
            // cantCopias="0"
            String sSQL="";
            String mensaje;
            String estado="PENDIENTE";
            String situacion="ACTIVO";
            ///campos a cargar
            idProve= txtIdProveedor.getText();
            tipoDePlan= "VARIABLE";
            fechaActual= fecha;
            idComprador= lblCompN.getText();
            sucursal= txtSucursal.getText();
            idRubro= ramosSelected.toString();
            motivoSNC= motivo_sncS;
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            fechaDesde= sdf1.format(dpFechaDesde.getDate()).toString();
            fechaHasta= sdf1.format(dpFechaHasta.getDate()).toString();
            accionComercial=txtAccionComercial.getText();
            obsProveedor= txtObsProveedor.getText();
            obsComprador=txtObsComprador.getText();
            mCancelacion=cmbModoCancelacion.getSelectedItem().toString();
            mImpacto=cmbImpacto.getSelectedItem().toString();
            mCanal=cmbCanal.getSelectedItem().toString();
            

            if (this.jrbMensual.isSelected()==true){
                tipoDeAplicacion="Mensual";
            }
            else{
                if (this.jrbSemanal.isSelected()==true){
                    tipoDeAplicacion="Semanal";}
            }
            idArt=null;
            //SETEAMOS EL DIA DE DEVENGAMIENTO
            Integer diaDev = setDiaDevengamiento();
            /*///creamos la consulta sql
            if (accion.equals("Insertar"))
            {
                sSQL="INSERT INTO plan_descuento (Proveedor_idproveedor, tipo_plan,fechaActual,"
                + "Usuario_idusuario,Sucursal_idSucursal,Sector_idsector,Motivo_SNC_idMotivo_SNC,"
                + "fecha_Devengamiento_Desde, fecha_Devengamiento_Hasta, accion_comercial,"
                + " aplicacion,dia_devengamiento,Articulo_idArticulo,lista_precio,estado,situacion,"
                + " obs_Proveedor, obs_Comprador, "
                + " Modo_Cancelacion ,Modo_Impacto, Modo_Canal) "  
                +"VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                
                mensaje="Operación Satisfactoria";
            }
            try
            {
                PreparedStatement pst= cn.prepareStatement(sSQL);
                pst.setString(1, idProve );
                pst.setString(2, tipoDePlan);
                pst.setString(3, fechaActual);
                pst.setString(4, idComprador);
                pst.setString(5, sucursal);
                pst.setString(6, idRubro);
                pst.setString(7, motivoSNC);
                pst.setString(8, fechaDesde);
                pst.setString(9, fechaHasta);
                pst.setString(10,accionComercial);
                pst.setString(11,tipoDeAplicacion);
                pst.setString(12,diaDev.toString());
                pst.setString(13,idArt);
                pst.setString(14,listaPre);
                pst.setString(15,estado);
                pst.setString(16,situacion);
                pst.setString(17,obsProveedor);
                pst.setString(18,obsComprador);
                pst.setString(19,mCancelacion);
                pst.setString(20,mImpacto);
                pst.setString(21,mCanal);

                int n = pst.executeUpdate();

                if (n>0)
                {
                    mensaje="Operación Satisfactoria";

                    JOptionPane.showMessageDialog(null, mensaje);

                    habilitar();//habilita los campos para la carga de datos
                    inhabilitar();*/
                    listaArticulos.clear();
                    SeleccionArticulosVariablesArray ventanaArticulos= new SeleccionArticulosVariablesArray(idProve,listaArticulos);
                    //ventanaArticulos.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    ventanaArticulos.setVisible(true);
                    //resetFormControls();
                          

       
        }
    }//GEN-LAST:event_btnSeleccionActionPerformed
    private Integer setDiaDevengamiento(){
        Integer valorDia=0;
        if(jrbMensual.isSelected()){
            //ESTA SELECCIONADO DEVENGAMIENTO MENSUAL
            valorDia=Integer.valueOf((String)cmbDevMes.getSelectedItem());
        }else{
            //ESTA SELECCIONADO DEVENGAMIENTO SEMANAL
            String valorCmb = cmbDevSem.getSelectedItem().toString();
            switch(valorCmb){
                case "Domingo": valorDia=1;
                                break;
                case "Lunes": valorDia=2;
                                break;
                case "Martes": valorDia=3;
                                break;
                case "Miercoles": valorDia=4;
                                break;
                case "Jueves": valorDia=5;
                                break;
                case "Viernes": valorDia=6;
                                break;
                case "Sabado": valorDia=7;
                                break;
            }
        }
        return valorDia;
    }
    private void jrbSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSemanalActionPerformed
        enableDevItems(2);
    }//GEN-LAST:event_jrbSemanalActionPerformed

///**JRADIOBOTTON DE LAS OPCIONES MENSUALES O SEMANALES
    private void jrbMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMensualActionPerformed
        enableDevItems(1);
    }//GEN-LAST:event_jrbMensualActionPerformed

    private void jcomSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomSucursalActionPerformed
        ///realizamos la conexion con la bdd.

        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();

        ///ingresamos la consulta
        String sSQL="", sucursal="";
        sucursal=(String) jcomSucursal.getSelectedItem();

        sSQL= "select idSucursal as id from sucursal where descripcion LIKE '%"+sucursal+"%'";

        try
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);

            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                try {
                    txtSucursal.setText(rs.getString("id"));
                } catch (IllegalStateException e) {}
            }

        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jcomSucursalActionPerformed

    private void jcomMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomMotivoActionPerformed
        ///realizamos la conexion con la bdd.

        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();

        ///ingresamos la consulta
        String sSQL="", motivo="";
        motivo=(String) jcomMotivo.getSelectedItem();

        sSQL= "select idmotivo_snc as id from motivo_snc where descripcion LIKE '%"+motivo+"%' order by id";

        try
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);

            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
               if(!jcomMotivo.getSelectedItem().toString().equals("")){
                //txtMotivoSNC.setText(rs.getString("id"));              
                motivo_sncS=rs.getString("id");
               }else{
                   //txtMotivoSNC.setText("");
                   motivo_sncS="";
               }
            }
            
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jcomMotivoActionPerformed

    private void jcomProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomProveedorActionPerformed

        ///realizamos la conexion con la bdd.

        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();

        ///ingresamos la consulta
        String sSQL="", razon="";
        razon=(String) jcomProveedor.getSelectedItem();

        sSQL= "select pr.idproveedor as id from proveedor as pr where pr.razon_social LIKE '%"+razon+"%' order by id";

        try
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);

            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                try {
                    txtIdProveedor.setText(rs.getString("id"));
                } catch (IllegalStateException e) {}
                //this.jcomArticulo.removeAllItems();
                //jcomClaseArticulo();

            }
            // jcomProveedor.transferFocus();
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jcomProveedorActionPerformed

    private void btnConsultasPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasPlanActionPerformed
        ConsultaVariables ventanaConsulta= new ConsultaVariables(UID);
        ventanaConsulta.setExtendedState(JFrame.MAXIMIZED_BOTH);
        ventanaConsulta.setVisible(true);
    }//GEN-LAST:event_btnConsultasPlanActionPerformed

    private void btnNuevoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPlanActionPerformed
        ///// HABILITA TODOS LOS PUNTOS NUEVAMENTE
        habilitar();
    }//GEN-LAST:event_btnNuevoPlanActionPerformed

    private void rbCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCompraActionPerformed
        // TODO add your handling code here:
        jcomClaseMotivoMenu(1);
    }//GEN-LAST:event_rbCompraActionPerformed

    private void rbVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVentaActionPerformed
        // TODO add your handling code here:
        jcomClaseMotivoMenu(2);
    }//GEN-LAST:event_rbVentaActionPerformed

    private void jcomRamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomRamosActionPerformed
        // TODO add your handling code here:
        if(jcomRamos.getSelectedIndex()!=-1){
            ramosSelected=ramosIdx[jcomRamos.getSelectedIndex()];
        }
    }//GEN-LAST:event_jcomRamosActionPerformed

    private void txtIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProveedorActionPerformed

    private void txtObsProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObsProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObsProveedorActionPerformed

    private void cmbModoCancelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbModoCancelacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbModoCancelacionActionPerformed

    private void cmbImpactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImpactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbImpactoActionPerformed

    private void cmbCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCanalActionPerformed

    private void jBaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceptarActionPerformed
        confirmarOP();
        
    }//GEN-LAST:event_jBaceptarActionPerformed
    private void resetFormControls(){
        dpFechaDesde.setDate(null);
        dpFechaHasta.setDate(null);
    }
    private void prepcmbDevs(){
        cmbDevMes.removeAllItems();
        cmbDevSem.removeAllItems();
        for(Integer cont=1;cont<=31;cont++){
            cmbDevMes.addItem(cont.toString());
        }
        cmbDevSem.addItem("Lunes");
        cmbDevSem.addItem("Martes");
        cmbDevSem.addItem("Miercoles");
        cmbDevSem.addItem("Jueves");
        cmbDevSem.addItem("Viernes");
        cmbDevSem.addItem("Sabado");
        cmbDevSem.addItem("Domingo");
        enableDevItems(1);
    }   
    private void enableDevItems(Integer btns){
        if(btns==1){
            cmbDevSem.setEnabled(false);
            lblTitDevSem.setEnabled(false);
            cmbDevMes.setEnabled(true);
            lblTitDevMes.setEnabled(true);
        }else{
            cmbDevSem.setEnabled(true);
            lblTitDevSem.setEnabled(true);
            cmbDevMes.setEnabled(false);
            lblTitDevMes.setEnabled(false);
        }
    }
    String accion="Insertar";

    private void loadCmbTPlan(Integer tipo){
        
    }
    
        /////////////////////////////////////////////////////////////////////////////
    //////////////CLASES PARA HABILITAR E INHABILITAR LOS MENUS//////////////////
    /////////////////////////////////////////////////////////////////////////////
    void habilitar(){
       
        //GENERO GRUPO DE RADIO BUTTONS
        lblListaPrecios.setEnabled(true);
        txtListaPrecios.setEnabled(true);
        txtRamos.setEnabled(true);
        jcomRamos.setEnabled(true);
        buttonGroup1.add(jrbMensual);
        buttonGroup1.add(jrbSemanal);
        btnGrpTipoPlan.add(rbCompra);
        btnGrpTipoPlan.add(rbVenta);
        jrbMensual.setSelected(true);
        rbCompra.setSelected(true);
        
        //CARGO EL COMBO DE TIPO SNC CON LAS COMPRAS
        loadCmbTPlan(1);
       ///Habilitar los botones.
       dpFechaDesde.setEnabled(true);
       dpFechaHasta.setEnabled(true);
       btnConsultasPlan.setEnabled(true);

       btnNuevoPlan.setEnabled(true);
       btnSalir.setEnabled(true);
       btnSeleccion.setEnabled(true);
       
        ///Habilitar los jCOMBOX
       //jcomArticulo.setEnabled(true);
       
       jcomMotivo.setEnabled(true);
       jcomProveedor.setEnabled(true);

       jcomSucursal.setEnabled(true);
       //impacto-canal-cancelacion
        txtModoImpacto.setEnabled(true);
        cmbImpacto.setEnabled(true);
        txtModoCancelacion.setEnabled(true);
        cmbModoCancelacion.setEnabled(true);
        txtCanal.setEnabled(true);
        cmbCanal.setEnabled(true);
       
       
       ///Habilitar las etiquetas.
       jlbAccion.setEnabled(true);
       jlbAplicacion.setEnabled(true);
       //jlbArticulo.setEnabled(true);
       
       lblPorcent.setEnabled(true);
       jlbDesde.setEnabled(true);
       jlbHasta.setEnabled(true);
       jlbMotivoSNC.setEnabled(true);
       jlbProveedor.setEnabled(true);

       jlbSucursal.setEnabled(true);
       jlbVigencia.setEnabled(true);
       jlbTitTipoMotSNC.setEnabled(true);
       ///Habilitar Radio botones
       jrbMensual.setEnabled(true);
       jrbSemanal.setEnabled(true);
       lblTitDev.setEnabled(true);
       lblTitDevMes.setEnabled(true);
       lblTitDevSem.setEnabled(true);
       cmbDevMes.setEnabled(true);
       cmbDevSem.setEnabled(true);
       rbCompra.setEnabled(true);
       rbVenta.setEnabled(true);
       txtObsProveedor.setEnabled(true);
        jlbObsProveedor.setEnabled(true);
        txtObsComprador.setEnabled(true);
        jlbObsComprador.setEnabled(true);
       
       
       ///Habilitar los TEXTFIELD
       txtAccionComercial.setEnabled(true);
       //txtArticulo.setEnabled(true);
      
       txtIdProveedor.setEnabled(true);
       
       //txtRubro.setEnabled(true);
       txtSucursal.setEnabled(true);
        
       txtIdProveedor.requestFocus();///posiciona el cursor
        
         //vacia los campos en ""
        txtIdProveedor.setText("");   
       
        txtIdProveedor.setText("");
        //txtRubro.setText("");
        
        txtSucursal.setText("");
        txtObsProveedor.setText("");
        txtObsComprador.setText("");
        //txtArticulo.setText(null);
        
    
        this.jcomProveedor.removeAllItems();
        this.jcomMotivo.removeAllItems();

        this.jcomSucursal.removeAllItems();
         
         
        ///Actualizamos los menus
        jcomClaseProveedorMenu();
        jcomClaseCompradorMenu();
        jcomClaseRamos();
        jcomClaseMotivoMenu(1);
        loadCmbModoCancelacion();
        loadCmbImpacto();
        loadCmbCanal();
        
        //jcomClaseArticulo();
        jcomClaseSucursal();
        enableDevItems(1);
    }
    private void jcomClaseRamos(){
        jcomRamos.removeAllItems();
       ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        ///ingresamos la consulta
        String sSQL= "SELECT id_ramo,descripcion_ramo FROM ramos order by id_ramo";
        Integer indice=0;
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomRamos.addItem(rs.getString("descripcion_ramo"));
                ramosIdx[indice]=rs.getInt("id_ramo");
                indice+=1;
            }            
                        
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    }
    
    void inhabilitar(){
       
       //Habilitar los botones.
       //btnConsultasPlan.setEnabled(false);
       dpFechaDesde.setEnabled(false);
       dpFechaDesde.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
       dpFechaHasta.setEnabled(false);
       dpFechaHasta.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
       lblListaPrecios.setEnabled(false);
        txtListaPrecios.setEnabled(false);
        txtRamos.setEnabled(false);
        jcomRamos.setEnabled(false);
       //btnNuevoPlan.setEnabled(false);
       //btnSalir.setEnabled(false);
       btnSeleccion.setEnabled(false);
       rbCompra.setEnabled(false);
       rbVenta.setEnabled(false);
       
        ///Habilitar los jCOMBOX
       //jcomArticulo.setEnabled(false);
       
       jcomMotivo.setEnabled(false);
       jcomProveedor.setEnabled(false);

       jcomSucursal.setEnabled(false);
       
       ///Habilitar las etiquetas.
       jlbAccion.setEnabled(false);
       jlbAplicacion.setEnabled(false);
       //jlbArticulo.setEnabled(false);
      
      lblPorcent.setEnabled(false);
       jlbDesde.setEnabled(false);
       jlbHasta.setEnabled(false);
       jlbMotivoSNC.setEnabled(false);
       jlbProveedor.setEnabled(false);

       jlbSucursal.setEnabled(false);
       jlbVigencia.setEnabled(false);
       jlbTitTipoMotSNC.setEnabled(false);
        ///Habilitar Radio botones
       jrbMensual.setEnabled(false);
       jrbSemanal.setEnabled(false);
       lblTitDev.setEnabled(false);
       lblTitDevMes.setEnabled(false);
       lblTitDevSem.setEnabled(false);
       cmbDevMes.setEnabled(false);
       cmbDevSem.setEnabled(false);
        ///Habilitar los TEXTFIELD
        
        txtAccionComercial.setEnabled(false);
        //txtArticulo.setEnabled(false);
       
        txtIdProveedor.setEnabled(false);
        
        //txtRubro.setEnabled(false);
        txtSucursal.setEnabled(false);
        
        ///Habilitar 
        //vacia los campos en ""
        txtIdProveedor.setText("");   
       
        txtIdProveedor.setText("");
        //txtRubro.setText("");
        
       
        txtSucursal.setText("");
        //txtArticulo.setText(null);
        //inhabiitar observaciones
        txtObsProveedor.setEnabled(false);
        jlbObsProveedor.setEnabled(false);
        txtObsComprador.setEnabled(false);
        jlbObsComprador.setEnabled(false);
         txtObsProveedor.setText("");
        txtObsComprador.setText("");
        //IMPACTO-CANCELACION-CANAL
         txtModoImpacto.setEnabled(false);
        cmbImpacto.setEnabled(false);
         txtModoCancelacion.setEnabled(false);
            cmbModoCancelacion.setEnabled(false);
         txtCanal.setEnabled(false);
         cmbCanal.setEnabled(false);
        
        
            }
    ////*Clases para actualizar los menús*////
     private void jcomClaseProveedorMenu()
    {
        ///realizamos la conexion con la bdd.
        
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        
        sSQL= "SELECT razon_social FROM proveedor order by 1";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomProveedor.addItem(rs.getString("razon_social"));
                
            }            
                        
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
    
    }
     private void jcomClaseCompradorMenu()
    {
       ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        
        sSQL= "select concat (apellido,\" \", nombre) as comprador from usuario where idUsuario='"+UID+"'";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.lblCompName.setText(rs.getString("comprador")); 
                lblCompN.setText(UID);
            }               
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }      
    
    }

    private void jcomClaseMotivoMenu(Integer tipo)
    {
        ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        jcomMotivo.removeAllItems();
        sSQL= "select descripcion from motivo_snc where tipo="+tipo+" order by descripcion";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            jcomMotivo.addItem("");
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomMotivo.addItem(rs.getString("descripcion")); 
            }               
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
    }
        
    private void jcomClaseSucursal(){
        
        ///realizamos la conexion con la bdd.
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        String idSuc=txtSucursal.getText();
        
        
        sSQL= "select descripcion from sucursal where sucursal.idSucursal like  '%"+idSuc+"%'";
        
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
                this.jcomSucursal.addItem(rs.getString("descripcion")); 
                
            }   
            
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
    
    private void loadCmbModoCancelacion(){
        cmbModoCancelacion.removeAllItems();
        this.cmbModoCancelacion.addItem("--SELECCIONAR--");
     
         String prov;
            //cadena a separar
            prov= cmbModoCancelacion.getSelectedItem().toString();
            //arreglo para guardar las cadenas separadas
            String[] parts=new String[3];
         
        ///ESTO DESCONCATENA EL STRING PROVEEDOR QUE VIENE CONCATENADO CON EL ID_PROV 
            
         if (!prov.equals("Item 1")){
                   int i=0;
                   parts[0]="NETEADO EN FACTURA";
                   parts[1]="NOTA DE CREDITO";
                   parts[2]="MERCADERIA SIN CARGO";
                   System.out.println(parts.length);
                   while (i<parts.length)///recorre cada valor de la consulta y la guarda en las variables.
                {
                        
                       String texto=(parts[i]);
                         this.cmbModoCancelacion.addItem(texto);
                         i++;
                    }
            }          
     
    }
    private void loadCmbImpacto(){
        cmbImpacto.removeAllItems();
        this.cmbImpacto.addItem("--SELECCIONAR--");
     
         String prov;
            //cadena a separar
            prov= cmbImpacto.getSelectedItem().toString();
            //arreglo para guardar las cadenas separadas
            String[] parts=new String[3];
         
        ///ESTO DESCONCATENA EL STRING PROVEEDOR QUE VIENE CONCATENADO CON EL ID_PROV 
            
         if (!prov.equals("Item 1")){
                   int i=0;
                   parts[0]="FORMADOR DE PRECIO";
                   parts[1]="RECUPERO ACCION";
                   parts[2]="INVERSIÓN SOBRE COMPRA";
                   System.out.println(parts.length);
                   while (i<parts.length)///recorre cada valor de la consulta y la guarda en las variables.
                {
                        
                       String texto=(parts[i]);
                         this.cmbImpacto.addItem(texto);
                         i++;
                    }
            }          
     
    }
    private void loadCmbCanal(){
        cmbCanal.removeAllItems();
        this.cmbCanal.addItem("--SELECCIONAR--");
     
         String prov;
            //cadena a separar
            prov= cmbCanal.getSelectedItem().toString();
            //arreglo para guardar las cadenas separadas
            String[] parts=new String[5];
         
        ///ESTO DESCONCATENA EL STRING PROVEEDOR QUE VIENE CONCATENADO CON EL ID_PROV 
            
         if (!prov.equals("Item 1")){
                   int i=0;
                   parts[0]="MAYORISTA";
                   parts[1]="EESS";
                   parts[2]="SAN JUSTO";
                   parts[3]="TODAS LAS SUCURSALES";
                   parts[4]="TOTAL COMPAÑÍA";
                   System.out.println(parts.length);
                   while (i<parts.length)///recorre cada valor de la consulta y la guarda en las variables.
                {
                        
                       String texto=(parts[i]);
                         this.cmbCanal.addItem(texto);
                         i++;
                    }
            }          
     
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanVariableSinDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanVariableSinDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanVariableSinDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanVariableSinDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private String userId;
            public void run() {
                new PlanVariableSinDev(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultasPlan;
    private javax.swing.ButtonGroup btnGrpTipoPlan;
    private javax.swing.JButton btnNuevoPlan;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCanal;
    private javax.swing.JComboBox<String> cmbDevMes;
    private javax.swing.JComboBox<String> cmbDevSem;
    private javax.swing.JComboBox<String> cmbImpacto;
    private javax.swing.JComboBox<String> cmbModoCancelacion;
    private org.jdesktop.swingx.JXDatePicker dpFechaDesde;
    private org.jdesktop.swingx.JXDatePicker dpFechaHasta;
    private javax.swing.JButton jBaceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JComboBox<String> jcomMotivo;
    private javax.swing.JComboBox<String> jcomProveedor;
    private javax.swing.JComboBox<String> jcomRamos;
    private javax.swing.JComboBox<String> jcomSucursal;
    private javax.swing.JLabel jlbAccion;
    private javax.swing.JLabel jlbAplicacion;
    private javax.swing.JLabel jlbDesde;
    private javax.swing.JLabel jlbHasta;
    private javax.swing.JLabel jlbMotivoSNC;
    private javax.swing.JLabel jlbObsComprador;
    private javax.swing.JLabel jlbObsProveedor;
    private javax.swing.JLabel jlbProveedor;
    private javax.swing.JLabel jlbSucursal;
    private javax.swing.JLabel jlbTitTipoMotSNC;
    private javax.swing.JLabel jlbVigencia;
    private javax.swing.JRadioButton jrbMensual;
    private javax.swing.JRadioButton jrbSemanal;
    private javax.swing.JLabel lblCompN;
    private javax.swing.JLabel lblCompName;
    private javax.swing.JLabel lblListaPrecios;
    private javax.swing.JLabel lblPorcent;
    private javax.swing.JLabel lblTitDev;
    private javax.swing.JLabel lblTitDevMes;
    private javax.swing.JLabel lblTitDevSem;
    private javax.swing.JRadioButton rbCompra;
    private javax.swing.JRadioButton rbVenta;
    private javax.swing.JTextField txtAccionComercial;
    private javax.swing.JLabel txtCanal;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtListaPrecios;
    private javax.swing.JLabel txtModoCancelacion;
    private javax.swing.JLabel txtModoImpacto;
    private javax.swing.JTextField txtObsComprador;
    private javax.swing.JTextField txtObsProveedor;
    private javax.swing.JLabel txtRamos;
    private javax.swing.JTextField txtSucursal;
    // End of variables declaration//GEN-END:variables
}
