/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modelos;

import BaseDeDatos.ConexionMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author usuario
 */
public class SeleccionArticulos extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionArticulos
     */
    private String IdProv;
    DefaultListModel<String> modelolista= new DefaultListModel<>();
    
    
    public SeleccionArticulos(String IdProveedor) {
        initComponents();
        IdProv=IdProveedor;
        System.out.println("EL PROVEEDOR SELECCIONADO ES :" + IdProveedor);
        jListArticulos.setModel(modelolista);
        jListArticulos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);        
        txtIdProveedor.setText(IdProveedor);
        jlistaArticulosClase();        
        txtIdProveedor.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBaceptar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBListarArticulos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListArticulos = new javax.swing.JList<>();
        txtIdProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selección de Artículos");

        jBaceptar.setText("Aceptar");
        jBaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaceptarActionPerformed(evt);
            }
        });

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBListarArticulos.setText("Mostrar Articulos");
        jBListarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarArticulosActionPerformed(evt);
            }
        });

        jListArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListArticulosMouseClicked(evt);
            }
        });
        jListArticulos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListArticulosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListArticulos);

        txtIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProveedorActionPerformed(evt);
            }
        });

        jLabel1.setText("idProveedor");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jBaceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(jBcancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBListarArticulos)))
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBListarArticulos)
                    .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBaceptar)
                    .addComponent(jBcancelar)
                    .addComponent(jButton1))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaceptarActionPerformed
        
        int index= 0;
        String articulo="";
       //conexión a la bdd
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        //STRING A UTILIZAR
        String ultimoId="", idArt="";
        String sSQL="",sSQLid="";
        String mensaje;
                
        ////Guardamos consulta para ultimo id.
        sSQLid="SELECT LAST_INSERT_ID(idPlan_Descuento) AS ProximoIdAInsertar FROM plan_descuento ORDER BY idPlan_Descuento DESC LIMIT 1";
        ///Guardamos la consulta para insertar el dato
        sSQL="INSERT INTO plan_articulo (idPlan_Descuento, idArticulo) " +
                "VALUES (?,?)";
        mensaje="Operación Satisfactoria";
        
        ///ARRANCA
        
        try 
        {
        PreparedStatement pst= cn.prepareStatement(sSQLid);
        ResultSet resultado= pst.executeQuery();
        while (resultado.next()) { //Es mas correcto poner el next en el while, te hace lo mismo que tenias en tu antiguo codigo pero en menos lineas y mas limpio
              ultimoId = resultado.getString("ProximoIdAInsertar");
              }
        System.out.println(ultimoId);
        
       ///obtenemos longitud de los elementos seleccionados. 
       index=jListArticulos.getSelectedValuesList().size();
      System.out.println(index);
        for (int i=0; i< index; i++ ){
           
           articulo=jListArticulos.getSelectedValuesList().get(i);
           String cortado[]=articulo.split("-");
           idArt= cortado[0];
           
           PreparedStatement pst2= cn.prepareStatement(sSQL);
           pst2.setString(1, ultimoId);
           pst2.setString(2, idArt);
           pst2.executeUpdate();
           
        }
        JOptionPane.showMessageDialog(null, mensaje);
        modelolista.clear();
        
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        
        }
      
        
    }//GEN-LAST:event_jBaceptarActionPerformed

    private void jBListarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarArticulosActionPerformed
       
        jlistaArticulosClase();
        
    }//GEN-LAST:event_jBListarArticulosActionPerformed
   
    private void jlistaArticulosClase (){
        
        ConexionMySQL mysql= new ConexionMySQL();
        Connection cn= mysql.Conectar();
        
       ///ingresamos la consulta
        String sSQL="";
        String idProv=txtIdProveedor.getText();
         modelolista.clear();
        
        //sSQL= "select CONCAT (idArticulo,'- ',descripcion) as descripcion from articulo where articulo.proveedor_idproveedor like  '%"+idProv+"%'";
        sSQL="select CONCAT (idArticulo,'- ',descripcion) as descripcion from articulo where idArticulo in (select idArticulo " +
                "from articulo_proveedor where idProveedor="+IdProv+")";
        System.out.println(sSQL);
        try 
        {
            Statement st= cn.createStatement();
            ResultSet rs= st.executeQuery(sSQL);
            
            while (rs.next())///recorre cada valor de la consulta y la guarda en las variables.
            {
             
              modelolista.addElement(rs.getString("descripcion"));
                        
            }   
            
        }
        catch (SQLException ex) {
            String mensaje= "Proveedor no contiene articulos";
            JOptionPane.showMessageDialog(null, mensaje);
        }
    
    }
    
    
    private void txtIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProveedorActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
         modelolista.clear();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      SeleccionArticulos.this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListArticulosMouseClicked
      
    }//GEN-LAST:event_jListArticulosMouseClicked

    private void jListArticulosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListArticulosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListArticulosValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            private String IdProveedor;
            public void run() {
                new SeleccionArticulos(IdProveedor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBListarArticulos;
    private javax.swing.JButton jBaceptar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListArticulos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtIdProveedor;
    // End of variables declaration//GEN-END:variables
}
